In [3]:
import numpy as np

# Create arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.arange(0, 10, 2)  # 0,2,4,6,8
arr3 = np.linspace(0, 1, 5) # 0, 0.25, 0.5, 0.75, 1
arr4 = np.random.rand(3, 3) # random 3x3

print("arr1:", arr1)
print("arr2:", arr2)
print("arr3:", arr3)
print("arr4:\n", arr4)

# Operations
print("Sum of arr1:", arr1.sum())
print("Mean of arr2:", arr2.mean())
print("Max of arr4:", arr4.max())
print("Std of arr4:", arr4.std())

# Indexing and slicing
print("First element of arr1:", arr1[0])
print("Slice arr2[1:3]:", arr2[1:3])
print("First column of arr4:\n", arr4[:, 0])


arr1: [1 2 3 4 5]
arr2: [0 2 4 6 8]
arr3: [0.   0.25 0.5  0.75 1.  ]
arr4:
 [[0.59537381 0.99628554 0.82807768]
 [0.93485268 0.77888335 0.49853652]
 [0.27817783 0.01545457 0.40496938]]
Sum of arr1: 15
Mean of arr2: 4.0
Max of arr4: 0.9962855406837996
Std of arr4: 0.3066428089150502
First element of arr1: 1
Slice arr2[1:3]: [2 4]
First column of arr4:
 [0.59537381 0.93485268 0.27817783]


In [50]:
arr5 = np.arange(1,21)
print("Sum:", arr5.sum())
print("Mean:", arr5.mean())
print("Min:", arr5.min())
print("Max:", arr5.max())

arr6 = np.random.randint(0,10,[5,5])
print(arr6)
print("Mean by rows:", arr6.mean(axis=1))
print("Mean by columns:", arr6.mean(axis=0))
arr6 = np.arange(10, 101, 10)
print(arr6[1::2])

Sum: 210
Mean: 10.5
Min: 1
Max: 20
[[2 2 7 4 1]
 [4 1 1 2 7]
 [7 8 7 3 9]
 [2 2 7 4 5]
 [0 8 9 2 4]]
Mean by rows: [3.2 3.  6.8 4.  4.6]
Mean by columns: [3.  4.2 6.2 3.  5.2]
[ 20  40  60  80 100]
